### ISSUE TITLE
Domain section bug

### ISSUE THREAD

**Issue by tripti033** [Eduhub-Community/eduhub-winter-cohort1.0#20]
android development point becomes hidden because of animation.

**Comment by Shubhcs01** [comment]
> android development point becomes hidden because of animation.

Hey Tripti, Thanks for mentioning this issue. 
Can you tell me on which device/screen dimension it occurs and if possible share the screenshot of the bug?

**Comment by tripti033** [comment]
hii, it would be difficult to take screenshot of animation but its occurring on my laptop screen.

**Comment by Shubhcs01** [comment]
> hii, it would be difficult to take screenshot of animation but its occurring on my laptop screen.

Tripti, I'm not able to observe that bug, it would be helpful if you can fix this issue

**Comment by tripti033** [comment]
made pull request.

**Comment by Shubhcs01** [comment]
> made pull request.

Great, Thanks. 👍
